### PR TITLE
[TASK] change logo

### PR DESCRIPTION
**Pull request by dermansi**
Changes the logo to a smaller one.

### CODE REVIEW

**Comment by Kanti** [comment]
How about this:
````
 __     __   ____  _    _   _ ______        _______ ____  _  __
| _| _ |_ | |  _ \| |  | | | / ___\ \      / | ____|  _ \| |/ /
| |_| |_| | | |_) | |  | | | \___ \\ \ /\ / /|  _| | |_) | ' / 
| |_   _| | |  __/| |__| |_| |___) |\ V  V / | |___|  _ <| . \ 
| | |_| | | |_|   |_____\___/|____/  \_/\_/  |_____|_| \_|_|\_\
|__|   |__|                                                    
````
or this:
````
 ___   _   ___   ___  _    _ _  ___  _ _ _  ___  ___  _ __
|  _|_| |_|_  | | . \| |  | | |/ __>| | | || __>| . \| / /
| | |_   _| | | |  _/| |_ | ' |\__ \| | | || _> |   /|  \ 
| |_  |_|  _| | |_|  |___|`___'<___/|__/_/ |___>|_\_\|_\_\
|___|     |___|                                           
````
or this:
````
 ____  __  ____      ______ _____   _______ _______ ________ _______ ______ __  __ 
|   _||  ||_   |    |   __ \     |_|   |   |     __|  |  |  |    ___|   __ \  |/  |
|  ||_    _||  |    |    __/       |   |   |__     |  |  |  |    ___|      <     < 
|  |_ |__| _|  |    |___|  |_______|_______|_______|________|_______|___|__|__|\__|
|____|    |____|                                                                   
````
or this:
````
    █ ▄▄  █       ▄      ▄▄▄▄▄    ▄ ▄   ▄███▄   █▄▄▄▄ █  █▀ 
    █   █ █        █    █     ▀▄ █   █  █▀   ▀  █  ▄▀ █▄█   
    █▀▀▀  █     █   █ ▄  ▀▀▀▀▄  █ ▄   █ ██▄▄    █▀▀▌  █▀▄   
    █     ███▄  █   █  ▀▄▄▄▄▀   █  █  █ █▄   ▄▀ █  █  █  █  
     █        ▀ █▄ ▄█            █ █ █  ▀███▀     █     █   
      ▀          ▀▀▀              ▀ ▀            ▀     ▀    
````
or this for Error:
````
    ██▓███   ██▓     █    ██   ██████  █     █░▓█████  ██▀███   ██ ▄█▀
   ▓██░  ██▒▓██▒     ██  ▓██▒▒██    ▒ ▓█░ █ ░█░▓█   ▀ ▓██ ▒ ██▒ ██▄█▒ 
   ▓██░ ██▓▒▒██░    ▓██  ▒██░░ ▓██▄   ▒█░ █ ░█ ▒███   ▓██ ░▄█ ▒▓███▄░ 
   ▒██▄█▓▒ ▒▒██░    ▓▓█  ░██░  ▒   ██▒░█░ █ ░█ ▒▓█  ▄ ▒██▀▀█▄  ▓██ █▄ 
   ▒██▒ ░  ░░██████▒▒▒█████▓ ▒██████▒▒░░██▒██▓ ░▒████▒░██▓ ▒██▒▒██▒ █▄
   ▒▓▒░ ░  ░░ ▒░▓  ░░▒▓▒ ▒ ▒ ▒ ▒▓▒ ▒ ░░ ▓░▒ ▒  ░░ ▒░ ░░ ▒▓ ░▒▓░▒ ▒▒ ▓▒
   ░▒ ░     ░ ░ ▒  ░░░▒░ ░ ░ ░ ░▒  ░ ░  ▒ ░ ░   ░ ░  ░  ░▒ ░ ▒░░ ░▒ ▒░
   ░░         ░ ░    ░░░ ░ ░ ░  ░  ░    ░   ░     ░     ░░   ░ ░ ░░ ░ 
                ░  ░   ░           ░      ░       ░  ░   ░     ░  ░   
````
or this:
````
  __     __   ____  _    _   _ ______        _______ ____  _  __
 | _| _ |_ | |  _ \| |  | | | / ___\ \      / / ____|  _ \| |/ /
 | |_| |_| | | |_) | |  | | | \___ \\ \ /\ / /|  _| | |_) | ' / 
 | |_   _| | |  __/| |__| |_| |___) |\ V  V / | |___|  _ <| . \ 
 | | |_| | | |_|   |_____\___/|____/  \_/\_/  |_____|_| \_\_|\_\
 |__|   |__|                                                    
````

**Comment by Lagerregal** [comment]
I prefer the first one ;-)

**Comment by dermansi** [comment]
It should be a small one, because it has to fit the putty/shell default window size

**Comment by dermansi** [comment]
Any news on this PR?

**Comment by Kanti** [comment]
@dermansi could you please change your PR to include the logo 1) from that list above?

**Comment by dermansi** [comment]
@xanti pluswerk should be written in small letters,
how about the following:

````
  __     __         _                             _    
 | _| _ |_ |  _ __ | |_   _ _____      _____ _ __| | __
 | |_| |_| | | '_ \| | | | / __\ \ /\ / / _ \ '__| |/ /
 | |_   _| | | |_) | | |_| \__ \\ V  V /  __/ |  |   < 
 | | |_| | | | .__/|_|\__,_|___/ \_/\_/ \___|_|  |_|\_\
 |__|   |__| |_|                                       
````

**Pull request merged**
